project:
  type: book
  output-dir: docs

book:
  title: "R para Ciencias Sociales y Gestión Pública"
  author: "Christian Chiroque Ruiz"
  date: "9/13/2025" #M/D/Y
  chapters:
    - index.qmd
    
    - part: Fundamentos de R
      chapters: 
        - c0_programas.qmd
        - c1_objetos.qmd
        - c2_manipulacion.qmd
        - c3_visualizacion.qmd
        - c4_transformacion.qmd

    - part: R Intermedio
      chapters: 
        - 2_c1_dashboards.qmd
        - 2_c2_shiny.qmd
        - 2_c3_rl.qmd

    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      dark: darkly
      light: flatly
  pdf:
    documentclass: scrreprt
lang: es

editor: visual

