# Sobre el curso {.unnumbered}

¡Bienvenidos al curso de Fundamentos de R para Ciencias Sociales y Gestión Pública!

Este curso está diseñado para ofrecer una introducción al uso del software R desde la perspectiva de la ciencia de datos. A lo largo del curso, trabajaremos en tres ejes principales:

1.  Fundamentos de programación en R: Aquí aprenderemos las definiciones y los fundamentos de programación que sustentan el funcionamiento del software R y los distintos algoritmos que utilizaremos.

2.  Herramientas para la manipulación de datos: En este eje, nos enfocaremos en la obtención, manipulación y transformación de datos, esenciales para trabajar con información de manera eficiente.

3.  Visualización de datos y reportes analíticos: Finalmente, estudiaremos los fundamentos para la visualización de datos y la elaboración de reportes analíticos, permitiéndonos comunicar nuestros hallazgos de manera clara y efectiva.

Puedes leer el detalle del contenido en el sílabo del curso colgado en la plataforma del Diplomado.

```{=html}
<iframe src="files/silabo.pdf" width="700" height="500" style="border: none;"></iframe>
```

## Sobre trabajo final

```{=html}
<iframe src="files/trabajo_grupal.pdf" width="700" height="500" style="border: none;"></iframe>
```
